### ISSUE TITLE
Desarrollo de Software

### ISSUE THREAD

**Issue by mariagfh1228** [SistemasTecTlaxiaco/actividad-1-infografia-mariagfh1228#2]
[Infografia Ciclo del Desarrollo de Software.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-infografia-mariagfh1228/files/9465634/Infografia.Ciclo.del.Desarrollo.de.Software.pdf)

**Comment by Valentiin01** [comment]
Calificación 19.5

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
